# Generated by Django 2.0.1 on 2018-02-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapphw1', '0003_auto_20180131_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.FloatField(default=1, verbose_name='coefficient of x^2 term')),
                ('b', models.FloatField(default=2, verbose_name='coefficient of x term')),
                ('c', models.FloatField(default=4, verbose_name='constant term')),
            ],
        ),
        migrations.DeleteModel(
            name='Zodiac',
        ),
    ]
